version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: postgres-db
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:${APP_PORT}'
    container_name: backend-api
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - .:/app
