version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    environment:
      - APP_PORT=${APP_PORT}
      - CORS_DOMAINS=${CORS_DOMAINS}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_TYPE=${DATABASE_TYPE}
    build:
      context: .
    ports:
      - '3000:${APP_PORT}'
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - .:/app
